omer_zaks = '''MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNmmmNNNNNNNNNmmNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMMMMMMMMMMMMMMNNNmmmmmmdmNNNNNNNNNmNNmmmNNNNNmmNNNNNNNNmmmNNNNNNNNmmmmmmddmmmmmmddhys
MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMMMNmddddddddddddmmNmmNNNNmmmdddmmmmdmmmmddddddNNNNNMMNNNmNmdhsossdNNNNmmmdh
MMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNMMMMMMMMMMMNNmmmmmmmdmmmmmmmmmmmmNMNmmmdddmmmmmmmmdddddmmNNNNNNMNNNdhs+/:://ohmmNNNNNm
MMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNMMMMMMNNNNmmmmdhddddddddddddddddmNNmmmmmdddmddddddddddmmNNNNNNNNNNhsoo+///++shdmmmNmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNMMMNNNNNmmhhhyyssssyhdddhddddhdddmmNNNmmdddddddddddddddddNNNMNNNNNNhysoo++++osyhmmdNmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMNNNmmmhhyysoooooosyyyyyyyhhddddmmmNNmNmmmmmmmmmmmmmNNNNNNMNMNNNNdhhyssoossyhddddddh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMNNNNNmdddhyssooo+++//+++++ooossyyhhddmNNNNNNNNNNNNNNmNNNNNNNNNNNNNNdddhhhhhhhyhhhyyyso
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmhhhyssoo+++/////////++++osshhhdmmNNNNmNNNNNNNNNNNNNNNNNNmNNNNddddddddddhhhhhyysy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmmdyysoo++////::::://///++ossyyhdmmNNmmdNNMNNNNNNNNNNNNNNmNNNNddddddmmddddmdhyhoo
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmhysso+++////::::://///++oossyyhdmNNmmmNNNNNNNNNNNNNNNNNmNNNNmmmmmmmmmmddmddhhyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmNmhysso+++///:::::::////+++ossyhhddmmmmmmmmmmmmmmmmmmmmmmmmNNmNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmNdyyyso++//:::::--:::::///+oosyhddmdmmmmmmmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNdhhhhyssoo+/:------://+++ossyyhmmmdmmmmmmmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmhhyooooooo+/::-:://+ooo++oyhyhmmNddmmmmmmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhmdhsossoss+++++/://++++ooooooyhhmNmddNmmmmmmNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNy+dhs//+++++//++o+++o++//+o++sosyhmhyddmmmmmmmmNNNNNNNNNNNNmmmmmmNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNhohy/:/+++////+oo+/+oo+////++ooosydo+hdmmmmmmmmNNmNNNNNNNNNmmmmmmNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNss/::++/////+ooo+/+oo+/////++oosyyosdmNmmmmmmmNNmNmNNNNNNNNmmmmmmNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNh/::++//////++oo//+oo+/////++ooohosmmNNNNNNNNNNNNNNNNNNNNNNNmmmmmNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNd/::/o+///////oo//:/+o+//////+ooshosysyydmNNNNNNNNNNNNNNNNNNNmmmmmNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNd+::/ys+++////+++/:-:/++/////++osys++o+ossyhddddmmmNNNNNNNNNNNNNNNmNNNNNNNmNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmds:-:/hyo++/////+++///+//////+++oy++////+oossssssssyhdmNNNNNNNNNNmmmmNNNNNmmNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhy+o:-::yy+/++++++++///+++++++++++ss//:::/+ooooooo++oossyhmNNNNNNNmmmmmNNNNmmmNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMNmdhyyssso+/-://:--:/+ooo++////++++++++oos///:::/+ooo++++++++ooosydNNNmmmmmmmmNNNNmNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMNdhyssssooo++:/:---:--/oooo++++ooso+/++osss/:::::/+++++///////++oosydNNmmmmmmmNNNNNmmNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMNdyssoooooooso+:-://+///+o+++++++oo+++oossso::::::/+++++/////////++osydNNmmmmmmmNNNNmmNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMNdyssooooo++sso+///::---:/++//+o++/+++sssooo+::::::/+++++//////////++osydNNmmmmmmmmNNNmNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMNmysoooo+++++o+/::--::::::://++/////+osso+++o::::-:::/+++++//////////++osymNNmmmmmmmNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMNNmhsooo+++++++++:----:/o++/:/++++++++oso+++++/::::-:::/++++++//////////++oshmNNmmmmNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMNNNNNNNNNhsoo++++++/+++++::::::/oo+//oooossoooo+++++o:::::-::::/+++++///////////++oshmNNmmmNNNNNNNNNNNNNNNN
MMMMMMMMNMMMMNNNMNNMMmyso++++////++++++/:----:/+//+///+osoooooooo+:::/:-:::::++++++///////////++oshmNNmmNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMNNNhso+++/////++++++o+::----://++////+sssssssso::::/:::::::/+++++++/////////+++oshmNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMNNNNNNyso+++///++++++++/+/::----:://+//+ooooosso+/:/:::::::::::/+++++++//////////+ooshmNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMNNNNNNNdyoo+++/+++++ooo++//+/:-----::/++/+++/+ooo+:::/:/::::::::::+++++++++////////++ooshmNNNNNNNNNNNNNNNNN
MMMMMMMMMNNNNNNNNNNNhsoo++++++++oosys++sy+/::---:/++/++++//++::::/::/::::::::::/++ooo++++////////+++osydNNNNNNNNNNNNNNNN
MMMMMMMNNNNNNNNNNMNdyso++++++++ooosddssyo/::::-::/+++//++++/://::/::/:::::::::::/+osyso++++///////+++osydNNNNNNNNNNNNNNN
MMMMMMNNNNNNNNNNNNdysoo+++++++oooosmmdssso/:--::://+//////////::/::::::::::::::::+oshhsoo++++//////++oosyhmNNNNNNNNNNNNN
MMMMNNNNNNNNNNNNNdyssoo++++++oooosymho+::+oo+/:::/+////:::/::::/:::::::::::::///:/oyhyysoo+++++/////++oosshmNNNNNNNNNNNN
MMMNNNNNNNNNNNNNdysoooo++++++oooshhs+//::-::+ooooo+/+:///::::://::/:::::/::://////+yyssysoo+++++/////+++ossydNNNNNNNNNNN
MMMMMNNNNNNNNNNdyssoooo+++++ooyhhs+///:::--::/+oo///+::////////::/:/::/://::////+++ossyyhsooo++++/////+++ossydNNNNNNNNNN
MMMNNNNNNNNNNNmhysoooo++++osyhhso+///:::::://+oo+///+::////////::/:/::/:////////++++oyyhhssooo++++////+++oossydNNNNNNNNN
NNNNNNNNNNNNNmhyssooo+++osyhyso++///::::::/+o+o+++//+::://////:://:/::/://////+++++ooosyysssooo+++++///+++oossydNNNNNNNN
NNNNNNNNNNNNmhyssooooosyhysso++++///:::://+osoo+/++o//::://///://///::////////+++++oooossssssooo+++++++++++oosyhmNNNNNNN
NNNNNNNNNNNmdyyssssyhhhysoo+++++///::::/+oo+oso+/+oo//::::///://////::///////++++oooooosysssssoo+++++++++++ooosyhNNNNNNN
NNNNNNNNNNNdhyhhhdddhysoo++++++////:://+syoo+os++/+o+//::::::://////::///+//++++ooooossshyyyyysoo+++++++++++oosyhdNNNNNN
NNNNNNNMNmddddddhhyysoo+++++++///////+oyhysooosso+++o+/:://:::///////:///++++++oooooossdmmmdmhssooo+++++++++oossyhmNNNNN
NNNNNNNNmdddhhyyyyssoo+++++++///////+sdhhhsoooossoo+oo+/:////////////////+++++ooooossssmmmmmmdyssoooo++++++oooosyydNNNNN
NNNNNNNmmdhhyyssssooo++++++++/////+oymmhhysoossysossssoo////+/////++////+++oooooooosssshmmmmmmhyssoooooo++ooooossyhmNNNN
NNNNNNmddhyysssssoo+++++++++++//++sdmmmhdysossoooosssysss+////++++++////+oooo+oooosssyymNNNNNNddhssoooooooooooossyydNNNN
NNNNNNddhyyssssoooo+++++++++++++ohmNNNdddyssysoooooossyyyyso+/+++ooo++++ooooo+oooosyyhmNNNNmmmmddhyssooooooooooossyhmNNN
NNNNNmdhhyyysssoooo++++++++++ooydNNNNNdddysysooooooooossyyyyysyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhyhhyyssooooooooossyhdNNN
NNNNNmdhyyysssoooooooooo++ooosdNNNNNmNdhdysyooooooossoosssyyyyyyyyyysssssyyyyyyyyyyyyyyyyysyyyssssssyssooooooossssyyhmNN
NNNNNddhhysssooooooooooooooshmNNNNNNNNddhyyyoooooooooosssossoossssssssssssssssssssssssssssssssssssssosssoooosssssssyhmNN
NNNNNdhyyysssoooooooooossyhmNNNNNNNNNmddhyyhysooooo+++o+++oo++oooooooooooooooooooooooooooooooooooooosssssssssssssssyhdNN
mmmmmdyysssssooooosossyhdmNNNNNNNNNNNNNmdhhhhysssooo++o+++oooooooooooooooooooooooooooooooooooooooooosssssssssssssssyhdNN
mmmmmhysssssooooossyhdddmddddddddddmdmmdddddddhhhhyyyysssyyyyyhhyyyyyyyssssssooooooooooooooooooooossssssssssssssssyyhmNN
mmmmmmhyssssooossyhddddddddddddddddddddddhhhhdhhhhhyy+::/syyyyhhhyhhhhhhhhhhhhhhyyyysssssssssssssssssssssssssssssyyhdNNN
mmmmmmmdyyssooosyhhhdddhdddhhhhdhdddhhdhhhhhddhyyyhy/::::syyyyyyhyyyyyyyyyyhhyyhhhhhdhhdhhhhhhhhyyyyyyyyyyyyyyyyyyhdmNNN
mmmmmmmmdhyooosyhhhhhhhhhhhhhhddddhhhhhdhhhhdhhyyys/::::+syyyyyyyhyyyyyyyyyyyyyyhyyyhdhhhhhhddmddddddddhhhhhhhhhdmdmmmmm
mmmmmmdddddhhhhhhhhhhhhhhhhhhddddhhhhhhhhhhhdhyyys/::::/:/oyyyyyyhyyyyyyyyyyyyyyhyyhhddhhhhhhhddddddddddddddddddmmmmmmmm'''